config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  root 'clients#index'

  devise_for :employees, skip: [:registrations, :passwords], controllers: { sessions: 'sessions' }
  devise_scope :employees do
    get 'change_password/:id', to: 'employees#change_password', as: :change_password
    get 'password/auth', to: 'password#auth'
    post 'password/auth', to: 'password#auth_action'
    get 'password/verify', to: 'password#verify'
    post 'password/verify', to: 'password#verify_action'
    get 'password/edit', to: 'password#edit'
    put 'password/update', to: 'password#update'
  end

  resources :page_elements
  resources :employees, except: [:show]
  resources :cuts, except: [:show, :destroy]
  resources :materials, except: [:show]
  resources :cities, except: [:show, :destroy]
  resources :details
  resources :roles, except: [:show, :destroy]
  resources :services, except: [:show]
  resources :delivery_payments

  resource :contacts, only: [:edit, :update]

  resources :individual_item, only: [:show] do
    resources :individual_item_shipments, only: [:index, :new, :create]
  end

  resources :individual_orders do
    put 'status_update', on: :member
  end

  resources :clients, except: [:destroy] do
    put 'ban', on: :member
    put 'unban', on: :member
    get 'edit_data', on: :member
  end

  scope :constructor, as: :constructor do
    get :options, to: 'constructor#options'
  end

  scope :constant, as: :constant do
    get :edit, to: 'constants#edit'
    put :update, to: 'constants#update'
  end
end

app/models/service.rb
class Service < ApplicationRecord
  mount_uploader :cover, CoverUploader
  mount_uploader :svg, CoverUploader

  validates_presence_of :title, :description
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :fetch_service, only: [:edit, :update, :destroy]
  before_action :authorize, except: [:index]

  def index
    @services = Service.all.order(title: :asc)
  end

  def new
    @service = Service.new
  end

  def create
    @service = Service.new(service_params)
    if @service.save
      redirect_to services_path
    else
      render :new
    end
  end

  def update
    if @service.update(service_params)
      redirect_to services_path
    else
      render :edit
    end
  end

  def destroy
    @service.destroy
    redirect_to services_path
  end

  private

  def fetch_service
    @service = Service.find(params[:id])
  end

  def service_params
    params.require(:service).permit(:title, :description, :cover, :svg)
  end
end

app/views/services/_form.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="<%= services_path %>"><i class="fa fa-list"></i> Продукция и услуги</a></li>
  <li class="breadcrumb-item active"><%= @service.title %></li>
</ol>

<%= form_for @service do |f| %>
  <%= f.label "Название"%>
  <%= f.text_field :title, required: true, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите название продукции или услуга" %>
  <%= f.label "Обложка"%>
  <%= f.file_field :cover, autofocus: true, label: false, class: 'form-control' %>
  <%= f.label "SVG"%>
  <%= f.file_field :svg, autofocus: true, label: false, class: 'form-control' %>
  <%= f.label "Описание" %>
  <%= f.cktext_area :description, required: true, ckeditor: { language: 'ru'} %>

  <div class="card-footer">
    <%= f.submit 'Сохранить', class: 'btn btn-primary'%>
  </div>
<% end %>

app/views/services/_service.html.erb
<tr>
  <td><%= service.title %></td>
  <td>
    <% if current_employee.allowed_to?(:edit, 'services') %>
      <%= link_to '', edit_service_path(service.id), class: "nav-icon fa fa-edit" %>
    <% end %>
  </td>
  <td>
    <% if current_employee.allowed_to?(:destroy, 'services') %>
      <%= link_to '', service_path(service.id), class: "nav-icon fa fa-remove", method: :delete, data: { confirm: 'Вы действительно хотите удалить страницу <' + service.title + '>?' } %>
    <% end %>
  </td>
</tr>

app/views/services/edit.html.erb
<%= render partial: 'form' %>

app/views/services/index.html.erb
<div class="row">
  <div class="col-12">
    <%= render_action_links(:create, 'services', 'Добавить продукцию или услугу', new_service_path) %>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center font-weight-bold">Продукция и услуги</h3>
      </div>
      <div class="card-body table-responsive p-0">
        <table class="table table-condensed">
          <tr>
            <th>Наименование</th>
            <th></th>
            <th></th>
          </tr>
					<%= render @services %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/services/new.html.erb
<%= render partial: 'form' %>