config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  root 'clients#index'

  devise_for :employees, skip: [:registrations, :passwords], controllers: { sessions: 'sessions' }
  devise_scope :employees do
    get 'change_password/:id', to: 'employees#change_password', as: :change_password
    get 'password/auth', to: 'password#auth'
    post 'password/auth', to: 'password#auth_action'
    get 'password/verify', to: 'password#verify'
    post 'password/verify', to: 'password#verify_action'
    get 'password/edit', to: 'password#edit'
    put 'password/update', to: 'password#update'
  end

  resources :page_elements
  resources :employees, except: [:show]
  resources :cuts, except: [:show, :destroy]
  resources :materials, except: [:show]
  resources :cities, except: [:show, :destroy]
  resources :details
  resources :roles, except: [:show, :destroy]
  resources :services, except: [:show]
  resources :delivery_payments

  resource :contacts, only: [:edit, :update]

  resources :individual_item, only: [:show] do
    resources :individual_item_shipments, only: [:index, :new, :create]
  end

  resources :individual_orders do
    put 'status_update', on: :member
  end

  resources :clients, except: [:destroy] do
    put 'ban', on: :member
    put 'unban', on: :member
    get 'edit_data', on: :member
  end

  scope :constructor, as: :constructor do
    get :options, to: 'constructor#options'
  end

  scope :constant, as: :constant do
    get :edit, to: 'constants#edit'
    put :update, to: 'constants#update'
  end
end

app/models/employee.rb
class Employee < ApplicationRecord
  devise :database_authenticatable, :rememberable, :trackable, :validatable

  sample_filter(
    id: {type: :number},
    name: {type: :string},
    email: {type: :string},
    phone_number: {type: :string},
    branch: {type: :string},
    sort: {
      type: :sorting,
      values: [:id, :name, :email, :branch],
      default_value: 'id_asc',
      hidden_input: true
    }
  )

  belongs_to :role

  enum status: [:active, :blocked]

  scope :without_current, ->(current_employee) {where.not(id: current_employee.id)}

  validates :email, presence: true, format: {with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i}
  validates :phone_number, presence: true, format: {with: /\A\d{8,9}\z/}
  validates :password, format: {without: /\p{Cyrillic}+/, message: 'Без кириллицы'}

  def allowed_to?(action, project_module = nil)
    return true if admin?
    AccessControl.allowed_actions(action, role, project_module)
  end

  def generate_sms_code!
    code = rand(100_000..999_999)
    self.update_column(:reset_password_token, code)
  end

  def generate_password_token!
    self.update_column(:reset_password_token, Devise.friendly_token)
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :find_employee, only: [:edit, :update, :change_password, :destroy]
  before_action :authorize

  def index
    @employees = Employee.without_current(current_employee).filtered(params[:sample_filter])
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    @employee.phone_number = sanitize_params_phone_number(employee_params[:phone_number])

    if @employee.save
      Notifications::CreateEmployeeWorker.perform_async(
        sanitize_db_phone_number(@employee.phone_number),
        employee_params[:password]
      )
      redirect_to employees_path, notice: 'Сотрудник добавлен'
    else
      render :edit
    end
  end

  def edit; end

  def update
    if @employee.update(employee_params)
      if employee_params[:password].present?
        Notifications::CreateEmployeeWorker.perform_async(
          sanitize_db_phone_number(@employee.phone_number),
          employee_params[:password]
        )
      end
      redirect_to employees_path, notice: 'Изменения применены'
    else
      render :edit
    end
  end

  def destroy
    @employee.destroy

    redirect_to employees_path
  end

  private

  def find_employee
    @employee = Employee.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def employee_params
    params.require(:employee).permit(
      :name, :email, :phone_number, :branch, :role_id,
      :telegram_id, :status, :password, :password_confirmation
    )
  end
end

app/views/employees/_employee.html.erb
<tr>
  <td><%= employee.id %></td>
  <td><%= employee.name %></td>
  <td><%= sanitize_db_phone_number(employee.phone_number) %></td>
  <td><%= employee.email %></td>
  <td><%= employee.branch %></td>
  <td><%= employee.role.name %></td>
  <td><% if employee.status == "active" %>
      <%= link_to '', employee_path(employee.id, employee: { status: "blocked" }), class: "nav-icon fa fa-lock", method: :put if current_employee.allowed_to?(:edit, 'employees') %>
    <% else %>
      <%= link_to '', employee_path(employee.id, employee: { status: "active" }), class: "nav-icon fa fa-unlock", method: :put if current_employee.allowed_to?(:edit, 'employees') %>
    <% end %>
  </td>
  <td><%= link_to '', edit_employee_path(employee.id), class: "nav-icon fa fa-edit" if current_employee.allowed_to?(:edit, 'employees') %></td>
  <td><%= link_to '', employee_path(employee.id), class: "nav-icon fa fa-remove", method: :delete, data: { confirm: 'Вы уверены, что хотите удалить сотрудника ' + employee.name + '?' } if current_employee.allowed_to?(:destroy, 'employees') %></td>
</tr>

app/views/employees/_form.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="<%= employees_path %>"><i class="fa fa-list"></i> Сотрудники</a></li>
  <li class="breadcrumb-item active"><%= @employee.name %></li>
</ol>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-primary">
        <%= form_for @employee do |f| %>
          <div class="card-body">
            <% if @employee.errors.present? %>
              <div class="form-errors-block">
                <ul>
                  <% @employee.errors.messages.each do |error| %>
                    <li><%= error.flatten.last %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <% unless @employee.new_record? %>
              <div class="hint">
                <h2><%= display_db_phone_number(@employee.phone_number) %></h2>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.label :name, "Имя"%>
              <%= f.text_field :name, required: false, autofocus: true, label: false, class: 'form-control'  %>
            </div>
            <div class="form-group">
              <%= f.label :email, "E-mail"%>
              <%= f.email_field :email, label: false, class: 'form-control' %>
            </div>
            <% if @employee.new_record? %>
              <div class="form-group">
                <%= f.label :phone_number, "Телефон"%>
                <%= f.text_field :phone_number, label: false, class: 'form-control phone_input', value: params.fetch(:employee, {})[:phone_number] %>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.label :branch, "Подразделение"%>
              <%= f.text_field :branch, label: false, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :telegram_id, "Telegram ID"%>
              <%= f.text_field :telegram_id, label: false, class: 'form-control' %>
            </div>
            <% if @employee.new_record? %>
              <div class="form-group">
                <%= f.label :password, "Пароль"%>
                <%= f.password_field :password, label: false, class: 'form-control' %>
              </div>
              <div class="form-group">
                <%= f.label :password_confirmation, "Повторите пароль" %>
                <%= f.password_field :password_confirmation, label: false, class: 'form-control' %>
              </div>
            <% end %>
            <div class="form-group">
              <%= f.label :role_id, "Роль" %>
              <%= f.select :role_id, options_from_collection_for_select(Role.all, :id, :name, @employee.role_id) %>
            </div>
          </div>
          <div class="card-footer">
            <%= f.submit "Сохранить", class: 'btn btn-primary' %>
            <%= link_to 'Поменять пароль', change_password_path(@employee), style: 'float: right; margin-top: 5px;' unless @employee.new_record? %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/employees/change_password.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title"><%= display_db_phone_number(@employee.phone_number) %></h3>
        </div>
        <%= form_for @employee, url: employee_path(@employee), method: :put do |f| %>
          <div class="card-body">
            <div class="form-group">
              <%= f.label :password, "Пароль"%>
              <%= f.password_field :password, label: false, class: 'form-control' %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, "Повторите пароль" %>
              <%= f.password_field :password_confirmation, label: false, class: 'form-control' %>
            </div>
          </div>
          <div class="card-footer">
            <%= f.submit "Изменить", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/employees/edit.html.erb
<%= render partial: 'form' %>

app/views/employees/index.html.erb
<div class="row">
  <div class="col-12">
    <%= render_action_links(:create, 'employees', 'Добавить сотрудника', new_employee_path) %>
    <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="collapse" data-target="#employees">Поиск</button>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center font-weight-bold">Список сотрудников</h3>
      </div>
      <div class="card-body table-responsive p-0">
        <div id="employees" class="collapse"><%= form_for_filter Employee %></div>
        <table class="table table-condensed">
          <tr>
            <th>ID <%= sort_link(Employee, :id) %></th>
            <th>Имя <%= sort_link(Employee, :name) %></th>
            <th>Телефон</th>
            <th>E-mail <%= sort_link(Employee, :email) %></th>
            <th scope="col">Подразделение <%= sort_link(Employee, :branch) %></th>
            <th>Роль</th>
            <th>Block</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          <%= render @employees %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/employees/new.html.erb
<%= render partial: 'form' %>