config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  root 'clients#index'

  devise_for :employees, skip: [:registrations, :passwords], controllers: { sessions: 'sessions' }
  devise_scope :employees do
    get 'change_password/:id', to: 'employees#change_password', as: :change_password
    get 'password/auth', to: 'password#auth'
    post 'password/auth', to: 'password#auth_action'
    get 'password/verify', to: 'password#verify'
    post 'password/verify', to: 'password#verify_action'
    get 'password/edit', to: 'password#edit'
    put 'password/update', to: 'password#update'
  end

  resources :page_elements
  resources :employees, except: [:show]
  resources :cuts, except: [:show, :destroy]
  resources :materials, except: [:show]
  resources :cities, except: [:show, :destroy]
  resources :details
  resources :roles, except: [:show, :destroy]
  resources :services, except: [:show]
  resources :delivery_payments

  resource :contacts, only: [:edit, :update]

  resources :individual_item, only: [:show] do
    resources :individual_item_shipments, only: [:index, :new, :create]
  end

  resources :individual_orders do
    put 'status_update', on: :member
  end

  resources :clients, except: [:destroy] do
    put 'ban', on: :member
    put 'unban', on: :member
    get 'edit_data', on: :member
  end

  scope :constructor, as: :constructor do
    get :options, to: 'constructor#options'
  end

  scope :constant, as: :constant do
    get :edit, to: 'constants#edit'
    put :update, to: 'constants#update'
  end
end

app/models/client.rb
class Client < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :password, format: {without: /\p{Cyrillic}+/, message: ' не может содержать кириллицу'}

  sample_filter(
    id: {type: :number},
    name: {type: :string},
    email: {type: :string},
    phone_number: {type: :string},
    sort: {
      type: :sorting,
      values: [:id, :name, :email],
      default_value: 'id_asc',
      hidden_input: true
    }
  )

  has_many :individual_orders

  enum status: [:active, :banned]
  enum person_type: [:individual, :legal]
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :fetch_client, only: %i[edit update show ban unban]
  before_action :authorize

  def index
    @clients = Client.filtered(params[:sample_filter])
  end

  def new
    @client = Client.new
  end

  def edit_data
    @client = Client.find(params[:id])
  end

  def create
    @client = Client.new(client_params)
    @client.phone_number = sanitize_params_phone_number(client_params[:phone_number])

    if @client.save
      redirect_to @client, notice: 'Клиент добавлен'
    else
      render :new
    end
  end

  def unban
    redirect_to clients_path, notice: 'Клиент разблокирован' if @client.update(ban_reason: nil, banned_before: nil)
  end

  def update
    if params[:client][:password].blank? && params[:client][:password_confirmation].blank?
      params[:client].delete(:password)
      params[:client].delete(:password_confirmation)
    end
    client_params[:phone_number].delete!(' ').gsub!('(+996)', '')
    if @client.update(client_params)
      redirect_to clients_path, notice: 'Данные клиента изменены'
    else
      render :edit
    end
  end

  private

  def fetch_client
    @client = Client.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def client_params
    params.require(:client).permit(
      :name, :last_name, :phone_number, :email, :password,
      :password_confirmation, :banned_before, :ban_reason, :discount
    )
  end
end

app/views/clients/_action.html.erb
<%= render_action_links(:edit, 'clients', 'Сбросить пароль', edit_client_path(client)) %>
<%= render_action_links(:show, 'clients', 'Просмотр', client_path(client)) %>
<%= render_action_links(:edit_data, 'clients', 'Редакт...', edit_data_client_path(client)) %>

<% if client.banned_before && client.banned_before > Date.today %>
  <%= render_action_links(:ban, 'clients', 'Разблокир...', unban_client_path(client), :put) %>
<% elsif current_employee.allowed_to?(:ban, 'clients') %>
  <button type="button" class="btn btn-sm btn-outline-primary mb-3 mr-3 float-right" data-toggle="modal" data-target="#modal-default-<%= client.id %>">
    Заблокир...
  </button>
<% end %>

<% if current_employee.allowed_to?(:ban, 'clients') %>
  <div class="modal fade" id="modal-default-<%= client.id %>" style="display: none;">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h3 class="card-title">Блокировка</h3>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <%= form_for client do |f| %>
          <div class="card-body">
            <div class="form-group">
              <%= f.label :banned_before, "Дата окончания блокировки"%>
              <%= f.date_field :banned_before, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите пароль" %>
            </div>
            <div class="form-group">
              <%= f.label :ban_reason, "Причина блокировки"%>
              <%= f.text_area :ban_reason, class: 'form-control' %>
            </div>
          </div>

          <div class="card-footer">
            <%= f.submit 'Заблокировать', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/clients/_client.html.erb
<tr>
  <td><%= client.id %></td>
  <td><%= client.name %> <%= client.last_name %></td>
  <td><%= sanitize_db_phone_number(client.phone_number) %></td>
  <td><%= client.email %></td>
  <td><%= render 'action', client: client %></td>
</tr>

app/views/clients/_form.html.erb
<%= form_for @client do |f| %>
  <div class="card-body">
    <div class="form-group">
      <%= f.label :name, "Имя"%>
      <%= f.text_field :name, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите имя клиента" %>
    </div>
    <div class="form-group">
      <%= f.label :last_name, "Фамилия"%>
      <%= f.text_field :last_name, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите фамилию клиента" %>
    </div>
    <div class="form-group">
      <%= f.label :phone_number, "Номер телефона"%>
      <%= f.text_field :phone_number, required: false, autofocus: true, label: false, id: "phone", type: "tel",
                       class: 'form-control phone_input' , placeholder:"Введите номер телефона клиента",
      value: ('996' + @client.phone_number if @client.phone_number) %>
    </div>
    <div class="form-group">
      <%= f.label :email, "E-Mail"%>
      <%= f.email_field :email, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите электронную почту клиента" %>
    </div>
    <div class="form-group">
      <%= f.label :discount, "Скидка(%)"%>
      <%= f.number_field :discount, max:"100", required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите скидку для клиента" %>
    </div>
    <% unless action_name == 'edit_data'  %>
      <div class="form-group">
        <%= f.label :password, "Пароль"%>
        <%= f.password_field :password, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите пароль" %>
      </div>
      <div class="form-group">
        <%= f.label :password_confirmation, "Подтверждение пароля"%>
        <%= f.password_field :password_confirmation, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите пароль" %>
      </div>
    <% end %>
  </div>

  <div class="card-footer">
    <%= f.submit class: 'btn btn-primary', value: "Сохранить изменения" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="<%= clients_path %>"><i class="fa fa-list"></i> Клиенты</a></li>
  <li class="breadcrumb-item active"><%= @client.name %> <%= @client.last_name %></li>
</ol>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Изменить пароль</h3>
        </div>
        <%= form_for @client do |f| %>
          <div class="card-body">
            <div class="form-group">
              <%= f.label :password, "Пароль"%>
              <%= f.password_field :password, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите пароль" %>
            </div>
            <div class="form-group">
              <%= f.label :password_confirmation, "Подтверждение пароля"%>
              <%= f.password_field :password_confirmation, required: false, autofocus: true, label: false, class: 'form-control' , placeholder:"Введите пароль" %>
            </div>
          </div>

          <div class="card-footer">
            <%= f.submit 'Обновить', class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/clients/edit_data.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="<%= clients_path %>"><i class="fa fa-list"></i> Клиенты</a></li>
  <li class="breadcrumb-item active"><%= @client.name %> <%= @client.last_name %></li>
</ol>

<%= render 'form' %>

app/views/clients/index.html.erb
<div class="row">
  <div class="col-12">
    <%= render_action_links(:create, 'clients', 'Добавить клиента', new_client_path) %>
    <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="collapse" data-target="#clients">Поиск</button>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center font-weight-bold">Список клиентов</h3>
      </div>
      <div class="card-body table-responsive p-0">
        <div id="clients" class="collapse"><%= form_for_filter Client %></div>
        <table class="table table-condensed">
          <tr>
            <th>ID <%= sort_link(Client, :id) %></th>
            <th>Имя <%= sort_link(Client, :name) %></th>
            <th>Телефон</th>
            <th>E-mail <%= sort_link(Client, :email) %></th>
            <th></th>
          </tr>
          <%= render @clients %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/clients/new.html.erb
<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Регистрация Клиента</h3>
        </div>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/clients/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="<%= clients_path %>"><i class="fa fa-list"></i> Клиенты</a></li>
  <li class="breadcrumb-item active"><%= @client.name %> <%= @client.last_name %></li>
</ol>

<div class="container-fluid">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card card-primary">
        <div class="card-header">
          <h3 class="card-title">Контактные данные: </h3>
        </div>
        <div class="card-body">
          <h4><%= @client.name %> <%= @client.last_name %></h4>

          <div>Номер телефона: <%= sanitize_db_phone_number(@client.phone_number) %></div>
          <div>E-Mail:         <%= @client.email %></div>
          <div>Наименование организации:         <%= @client.company_name %></div>
          <div>Юридический адрес:         <%= @client.company_legal_address %></div>
          <div>Фактический адрес:         <%= @client.company_address %></div>
          <div>ИНН:         <%= @client.company_INN %></div>
          <div>Код ОКПО:         <%= @client.company_OKPO %></div>
          <div>Наименование банка:         <%= @client.bank_name %></div>
          <div>Расчетный счет:         <%= @client.settlement_account %></div>
          <div>Город Банка:         <%= @client.city %></div>
          <div>БИК:         <%= @client.company_BIC %></div>
          <div>Скидка(%):         <%= @client.discount %></div>
          <div></br>
            <% if @client.banned_before && @client.banned_before > Date.today %>
                Пользователь заблокирован до <%= @client.banned_before.strftime('%Y-%m-%d') %></br>
                Причина:
                <%= @client.ban_reason %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>