config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  mount Sidekiq::Web => '/sidekiq'

  root 'clients#index'

  devise_for :employees, skip: [:registrations, :passwords], controllers: { sessions: 'sessions' }
  devise_scope :employees do
    get 'change_password/:id', to: 'employees#change_password', as: :change_password
    get 'password/auth', to: 'password#auth'
    post 'password/auth', to: 'password#auth_action'
    get 'password/verify', to: 'password#verify'
    post 'password/verify', to: 'password#verify_action'
    get 'password/edit', to: 'password#edit'
    put 'password/update', to: 'password#update'
  end

  resources :page_elements
  resources :employees, except: [:show]
  resources :cuts, except: [:show, :destroy]
  resources :materials, except: [:show]
  resources :cities, except: [:show, :destroy]
  resources :details
  resources :roles, except: [:show, :destroy]
  resources :services, except: [:show]
  resources :delivery_payments

  resource :contacts, only: [:edit, :update]

  resources :individual_item, only: [:show] do
    resources :individual_item_shipments, only: [:index, :new, :create]
  end

  resources :individual_orders do
    put 'status_update', on: :member
  end

  resources :clients, except: [:destroy] do
    put 'ban', on: :member
    put 'unban', on: :member
    get 'edit_data', on: :member
  end

  scope :constructor, as: :constructor do
    get :options, to: 'constructor#options'
  end

  scope :constant, as: :constant do
    get :edit, to: 'constants#edit'
    put :update, to: 'constants#update'
  end
end

app/models/individual_order.rb
class IndividualOrder < ApplicationRecord
  include TemirtulparHelper::Model::IndividualOrder

  def self.filter_statuses
    Hash[STATUSES.map.with_index.to_a]
  end

  def self.filter_person_types
    Hash[PERSON_TYPE.map.with_index.to_a]
  end

  sample_filter(
    {
      id: { type: :number },
      name: { type: :string },
      last_name: { type: :string },
      person_type: { type: :list, values: filter_person_types },
      status: { type: :list, values: filter_statuses },
      created_at: { type: :date },
      updated_at: { type: :date },
      sort: {
        type: :sorting,
        values: [:id, :name, :last_name, :created_at, :updated_at],
        default_value: 'updated_at_desc',
        hidden_input: true
      }
    }
  )

  has_many :individual_items
  has_many :order_histories

  belongs_to :client

  enum person_type: PERSON_TYPE
  enum payment: PAYMENT
  enum delivery_method: DELIVERY_METHODS
  enum status: STATUSES

  def shipped?
    in_progress?
  end
end

app/controllers/individual_orders_controller.rb
class IndividualOrdersController < ApplicationController
  before_action :fetch_order, only: [:status_update]
  before_action :authorize, except: :status_update

  def index
    @individual_orders = IndividualOrder.where(status: available_statuses).filtered(params[:sample_filter])
  end

  def show
    @individual_order = IndividualOrder.find(params[:id])
    @statuses = statuses_for_updates
    respond_pdf
  end

  def status_update
    OrderStatusUpdate.new(current_employee, @order, params).run
    redirect_to @order, notice: 'Статус заказа успешно обновлен!'
  rescue Errors::PermissionError
    redirect_to @order, alert: 'Не хватает прав на изменение заказа'
  end

  private

  def respond_pdf
    respond_to do |format|
      format.html
      format.pdf do
        pdf = OrderPdf.new(@individual_order)
        send_data pdf.render, filename: "заказ_#{@individual_order.id}.pdf", type: 'application/pdf'
      end
    end
  end

  def fetch_order
    @order = IndividualOrder.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

  def statuses_for_updates
    if current_employee.admin?
      IndividualOrder.statuses.keys
    else
      current_employee.role.permission['order_statuses_on']
    end
  end

  def available_statuses
    if current_employee.admin?
      IndividualOrder.statuses.keys
    elsif current_employee.role
      arr = []
      arr << current_employee.role.permission['order_statuses_on']
      arr << current_employee.role.permission['order_statuses_with']
      arr.flatten.compact
    end
  end
end

app/helpers/individual_order_helper.rb
module IndividualOrderHelper
  def check_order_permission(individual_order)
    current_employee.admin? ||
    current_employee.role.permission['order_statuses_with'] &&
    current_employee.role.permission['order_statuses_with'].include?(individual_order.status) &&
    current_employee.role.permission['order_statuses_on'].present?
  end

  def order_status_color(status)
    case status
    when 'pending_payment'
      'label-info'
    when 'paid'
      'label-primary'
    when 'in_progress'
      'label-warning'
    when 'canceled'
      'label-danger'
    when 'finished'
      'label-success'
    when 'proof_payment'
      'label-success'
    when 'payment_error'
      'label-danger'
    end
  end
end

app/views/individual_orders/_individual_order.html.erb
<tr>
  <td><%= link_to pretty_id(individual_order.id), individual_order_path(individual_order) %></td>
  <td>
    <% if individual_order.individual? %>
      <span class='label label-primary'>Физ</span>
    <% elsif individual_order.legal? %>
      <span class='label label-warning'>Юр</span>
    <% end %>
  </td>
  <% if current_employee.allowed_to?(:show, 'clients') %>
    <td><%= link_to individual_order.name, client_path(individual_order.client_id) %></td>
    <td><%= link_to individual_order.last_name, client_path(individual_order.client_id) %></td>
  <% else %>
    <td><%= individual_order.name %></td>
    <td><%= individual_order.last_name %></td>
  <% end %>
  <td><%= sanitize_db_phone_number(individual_order.phone_number) %></td>
  <td><%= individual_order.email %></td>
  <td>
    <span class="label <%= order_status_color(individual_order.status) %>">
      <%= humanize_order_status(individual_order.status) %>
    </span>
  </td>
  <td><%= display_datetime(individual_order.created_at) %></td>
  <td><%= display_datetime(individual_order.updated_at) %></td>
</tr>

app/views/individual_orders/_order_history.html.erb
<li>
  <div class="datetime"><%= display_datetime(order_history.created_at) %></div>
  <% if order_history.employee.present? %>
    <%= order_history.employee.name %> изменил статус "<%= t("permissions.order_statuses_with.#{order_history.status_from}") %>" на "<%= t("permissions.order_statuses_on.#{order_history.status_to}") %>"
  <% else %>
    Клиент изменил статус на "<%= t("permissions.order_statuses_on.#{order_history.status_to}") %>"
  <% end %>
</li>

app/views/individual_orders/index.html.erb
<div class="row">
  <div class="col-12">
    <button type="button" class="btn btn-sm btn-outline-primary" data-toggle="collapse" data-target="#orders">Поиск</button>
    <p></p>
  </div>
  <div class="col-12">
    <div class="card">
      <div class="card-header">
        <h3 class="card-title text-center font-weight-bold">Список заказов:</h3>
      </div>
      <div class="card-body table-responsive p-0">
        <div id="orders" class="collapse"><%= form_for_filter IndividualOrder %></div>
        <table class="table table-condensed">
          <tr>
            <th width="170">ID Заказа <%= sort_link(IndividualOrder, :id) %></th>
            <th>Тип</th>
            <th width="150">Имя <%= sort_link(IndividualOrder, :name) %></th>
            <th width="150">Фамилия <%= sort_link(IndividualOrder, :last_name) %></th>
            <th>Номер телефона</th>
            <th>Email</th>
            <th>Статус</th>
            <th width="200">Дата создания <%= sort_link(IndividualOrder, :created_at) %></th>
            <th width="220">Дата изменения <%= sort_link(IndividualOrder, :updated_at) %></th>
          </tr>
					<%= render @individual_orders %>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/individual_orders/show.html.erb
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="<%= individual_orders_path %>"><i class="fa fa-list"></i> Заказы</a></li>
  <li class="breadcrumb-item active">Заказ #<%= pretty_id(@individual_order.id) %></li>
</ol>

<div class="invoice p-3 mb-3">
  <div class="row">
    <div class="col-12">
      <h4>
        <i class="fa fa-hashtag "></i> <%= pretty_id(@individual_order.id) %>
        <div class="float-right">
          <% if check_order_permission(@individual_order) %>
            <button type="button" class="btn btn-outline-primary" data-toggle="modal" data-target="#modal-default">
              Сменить статус
            </button>
            <%= link_to 'PDF', individual_order_path(@individual_order.id, format: :pdf), class: 'btn btn-outline-primary' %>
          <% end %>
        </div>
      </h4>
    </div>
  </div>

  <div class="row invoice-info">
    <div class="col-sm-6 invoice-col">
      <b>Статус:</b> <span class="label <%= order_status_color(@individual_order.status) %>"><%= humanize_order_status(@individual_order.status) %></span><br>
      <% if @individual_order.individual? %>
        <br>
        <b>Оформлен на физическое лицо</b><br>
        <b>Клиент:</b>
        <% if current_employee.allowed_to?(:show, 'clients') %>
          <%= link_to "#{@individual_order.last_name} #{@individual_order.name}", client_path(@individual_order.client_id) %>
        <% else %>
          <%= @individual_order.last_name %> <%= @individual_order.name %>
        <% end %>
        <br>
        <b>Номер телефона:</b> <%= @individual_order.phone_number %><br>
        <b>E-Mail:</b>         <%= @individual_order.email %><br>
      <% else %>
        <br>
        <b>Оформлен на юридическое лицо</b><br>
        <b>Клиент:</b>
        <% if current_employee.allowed_to?(:show, 'clients') %>
          <%= link_to "#{@individual_order.last_name} #{@individual_order.name}", client_path(@individual_order.client_id) %>
        <% else %>
          <%= @individual_order.last_name %> <%= @individual_order.name %>
        <% end %>
        <br>
        <b>Контактное лицо:</b>   <%= @individual_order.contact_person_name %> <%= @individual_order.contact_person_last_name %><br>
        <b>Номер телефона:</b>    <%= @individual_order.contact_person_phone_number %><br>
        <b>E-Mail:</b>            <%= @individual_order.contact_person_email %><br>
        <b>Компания:</b>          <%= @individual_order.company_name %><br>
        <b>ИИН:</b>               <%= @individual_order.company_INN %><br>
        <b>БИК:</b>               <%= @individual_order.company_BIC %><br>
        <b>Код ОКПО:</b>          <%= @individual_order.company_OKPO %><br>
        <b>Юридический адрес:</b> <%= @individual_order.company_legal_address %><br>
        <b>Фактический адрес:</b> <%= @individual_order.company_address %><br>
        <b>Банк:</b>              <%= @individual_order.bank_name %><br>
        <b>Адрес банка:</b>       <%= @individual_order.bank_address %><br>
        <b>Расчетный счет:</b>    <%= @individual_order.settlement_account %><br>
      <% end %>
      <b>Дата создания:</b> <%= display_datetime(@individual_order.created_at) %><br>
      <b>Дата последнего изменения:</b> <%= display_datetime(@individual_order.updated_at) %><br><br>
      <b>История заказа:</b>
      <ul class="order_history_list">
        <%= render collection: @individual_order.order_histories.order(created_at: :asc), partial: 'individual_orders/order_history' %>
      </ul>
    </div>

    <div class="col-sm-6 invoice-col">
      <b>Комментарий к заказу:</b><br>
      <%= @individual_order.comment %>
    </div>
  </div>

  <br><br>

  <div class="row">
    <div class="col-12">
      <h4>Список деталей:</h4>
    </div>
  </div>

  <div class="row">
    <div class="col-12 table-responsive">
      <table class="table table-striped details-table">
        <thead>
        <tr>
          <th width=120></th>
          <th>ID</th>
          <th>Название</th>
          <th>Материал</th>
          <th>Тип резки</th>
          <th>Кол-во</th>
          <th>Отгружено</th>
          <th></th>
        </tr>
        </thead>
        <tbody>
          <%= render @individual_order.individual_items %>
        </tbody>
      </table>
    </div>
  </div>
</div>

<% if @statuses.present? %>
  <div class="modal fade" id="modal-default" style="display: none;">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h4>Изменить статус</h4>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <%= form_for @individual_order, url: status_update_individual_order_path(@individual_order), method: :put do |f| %>
          <div class="modal-body">
            <div class="card-body">
              <div class="form-group">
                <%= f.label :status, "Статус"%>
                <%= f.select :status, @statuses.collect {|s| [ humanize_order_status(s), s ] } %>
              </div>
            </div>
          </div>
          <div class="modal-footer">
            <%= f.submit "Изменить", class: 'btn btn-primary' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
<% end %>